/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package victoria.vista;

import java.awt.Dimension;
import java.awt.Image;
import java.awt.Graphics;
import javax.swing.ImageIcon;
import victoria.entidad.util.Sesion;

/**
 *
 * @author andres.silva
 */
public class home extends javax.swing.JFrame {

    public static Sesion sesSesion;

    /**
     * Creates new form home
     */
    public home() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem7 = new javax.swing.JMenuItem();
        ImageIcon icon= new ImageIcon(getClass().getResource("/images/fondo.JPG"));
        Image image = icon.getImage();
        jdpHome = new javax.swing.JDesktopPane(){
            public void paintComponent(Graphics g) {
                g.drawImage(image,0,0,getWidth(),getHeight(),this);
            }
        };
        jMenuBar1 = new javax.swing.JMenuBar();
        mnuInicio = new javax.swing.JMenu();
        jMenuItem8 = new javax.swing.JMenuItem();
        mnuMantenimiento = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        mnuProceso = new javax.swing.JMenu();
        jMenuItem6 = new javax.swing.JMenuItem();

        jMenuItem7.setText("jMenuItem7");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Victoria 1.0");
        setLocation(new java.awt.Point(100, 100));
        setPreferredSize(new java.awt.Dimension(700, 500));
        setSize(new java.awt.Dimension(200, 200));

        jdpHome.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jdpHome.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentShown(java.awt.event.ComponentEvent evt) {
                jdpHomeComponentShown(evt);
            }
        });

        javax.swing.GroupLayout jdpHomeLayout = new javax.swing.GroupLayout(jdpHome);
        jdpHome.setLayout(jdpHomeLayout);
        jdpHomeLayout.setHorizontalGroup(
            jdpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );
        jdpHomeLayout.setVerticalGroup(
            jdpHomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 478, Short.MAX_VALUE)
        );

        mnuInicio.setText("Inicio");

        jMenuItem8.setText("Login");
        jMenuItem8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem8ActionPerformed(evt);
            }
        });
        mnuInicio.add(jMenuItem8);

        jMenuBar1.add(mnuInicio);

        mnuMantenimiento.setText("Mantenimiento");

        jMenuItem1.setText("Producto");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        mnuMantenimiento.add(jMenuItem1);

        jMenuItem2.setText("Tipo");
        mnuMantenimiento.add(jMenuItem2);

        jMenuItem3.setText("Unidad Medida");
        mnuMantenimiento.add(jMenuItem3);

        jMenuItem4.setText("Productor");
        mnuMantenimiento.add(jMenuItem4);

        jMenuItem5.setText("Destino");
        mnuMantenimiento.add(jMenuItem5);

        jMenuBar1.add(mnuMantenimiento);

        mnuProceso.setText("Proceso");

        jMenuItem6.setText("Terminados");
        mnuProceso.add(jMenuItem6);

        jMenuBar1.add(mnuProceso);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpHome)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jdpHome, javax.swing.GroupLayout.Alignment.TRAILING)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jdpHomeComponentShown(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jdpHomeComponentShown
        // TODO add your handling code here:

    }//GEN-LAST:event_jdpHomeComponentShown

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jMenuItem8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem8ActionPerformed
        // TODO add your handling code here:
        login frmLogin = new login();
        Dimension desktopSize = jdpHome.getSize();
        Dimension jInternalFrameSize = frmLogin.getSize();
        frmLogin.setLocation((desktopSize.width - jInternalFrameSize.width) / 2,
                (desktopSize.height - jInternalFrameSize.height) / 2);
        jdpHome.add(frmLogin);
        mnuInicio.setEnabled(false);
        mnuMantenimiento.setEnabled(false);
        mnuProceso.setEnabled(false);
        frmLogin.show();
    }//GEN-LAST:event_jMenuItem8ActionPerformed

    public static void AsignaMenu(Sesion inSesSesion, String inStrRol) {
        if (inStrRol.compareTo("ADMINISTRADOR") == 0) {
            mnuInicio.getItem(0).setEnabled(false);
            mnuMantenimiento.setVisible(true);
            mnuProceso.setVisible(true);
            mnuInicio.setEnabled(true);
            mnuMantenimiento.setEnabled(true);
            mnuProceso.setEnabled(true);
            sesSesion = inSesSesion;
        }
        if (inStrRol.compareTo("USUARIO") == 0) {
            mnuInicio.getItem(0).setEnabled(false);
            mnuProceso.setVisible(true);
            mnuProceso.setEnabled(true);
            sesSesion = inSesSesion;
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(home.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new home().setVisible(true);
                mnuMantenimiento.setVisible(false);
                mnuProceso.setVisible(false);

            }
        });
    }

    public static Sesion getSesSesion() {
        return sesSesion;
    }

    public static void setSesSesion(Sesion sesSesion) {
        home.sesSesion = sesSesion;
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenuItem jMenuItem7;
    public static javax.swing.JMenuItem jMenuItem8;
    public static javax.swing.JDesktopPane jdpHome;
    public static javax.swing.JMenu mnuInicio;
    public static javax.swing.JMenu mnuMantenimiento;
    public static javax.swing.JMenu mnuProceso;
    // End of variables declaration//GEN-END:variables
}
